// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: chamber_agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentEvent_Started
	//	*AgentEvent_TextDelta
	//	*AgentEvent_Completed
	//	*AgentEvent_Error
	//	*AgentEvent_ApprovalRequest
	//	*AgentEvent_LensChanged
	Payload       isAgentEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_chamber_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chamber_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_chamber_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentEvent) GetPayload() isAgentEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentEvent) GetStarted() *Started {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *AgentEvent) GetTextDelta() *TextDelta {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_TextDelta); ok {
			return x.TextDelta
		}
	}
	return nil
}

func (x *AgentEvent) GetCompleted() *Completed {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

func (x *AgentEvent) GetError() *RuntimeError {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *AgentEvent) GetApprovalRequest() *ApprovalRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_ApprovalRequest); ok {
			return x.ApprovalRequest
		}
	}
	return nil
}

func (x *AgentEvent) GetLensChanged() *LensChanged {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_LensChanged); ok {
			return x.LensChanged
		}
	}
	return nil
}

type isAgentEvent_Payload interface {
	isAgentEvent_Payload()
}

type AgentEvent_Started struct {
	Started *Started `protobuf:"bytes,2,opt,name=started,proto3,oneof"`
}

type AgentEvent_TextDelta struct {
	TextDelta *TextDelta `protobuf:"bytes,3,opt,name=text_delta,json=textDelta,proto3,oneof"`
}

type AgentEvent_Completed struct {
	Completed *Completed `protobuf:"bytes,4,opt,name=completed,proto3,oneof"`
}

type AgentEvent_Error struct {
	Error *RuntimeError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type AgentEvent_ApprovalRequest struct {
	ApprovalRequest *ApprovalRequest `protobuf:"bytes,7,opt,name=approval_request,json=approvalRequest,proto3,oneof"`
}

type AgentEvent_LensChanged struct {
	LensChanged *LensChanged `protobuf:"bytes,8,opt,name=lens_changed,json=lensChanged,proto3,oneof"`
}

func (*AgentEvent_Started) isAgentEvent_Payload() {}

func (*AgentEvent_TextDelta) isAgentEvent_Payload() {}

func (*AgentEvent_Completed) isAgentEvent_Payload() {}

func (*AgentEvent_Error) isAgentEvent_Payload() {}

func (*AgentEvent_ApprovalRequest) isAgentEvent_Payload() {}

func (*AgentEvent_LensChanged) isAgentEvent_Payload() {}

type HostMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HostMessage_Prompt
	//	*HostMessage_ApprovalDecision
	Payload       isHostMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMessage) Reset() {
	*x = HostMessage{}
	mi := &file_chamber_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMessage) ProtoMessage() {}

func (x *HostMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chamber_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMessage.ProtoReflect.Descriptor instead.
func (*HostMessage) Descriptor() ([]byte, []int) {
	return file_chamber_agent_proto_rawDescGZIP(), []int{1}
}

func (x *HostMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HostMessage) GetPayload() isHostMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HostMessage) GetPrompt() *UserPrompt {
	if x != nil {
		if x, ok := x.Payload.(*HostMessage_Prompt); ok {
			return x.Prompt
		}
	}
	return nil
}

func (x *HostMessage) GetApprovalDecision() *ApprovalDecision {
	if x != nil {
		if x, ok := x.Payload.(*HostMessage_ApprovalDecision); ok {
			return x.ApprovalDecision
		}
	}
	return nil
}

type isHostMessage_Payload interface {
	isHostMessage_Payload()
}

type HostMessage_Prompt struct {
	Prompt *UserPrompt `protobuf:"bytes,2,opt,name=prompt,proto3,oneof"`
}

type HostMessage_ApprovalDecision struct {
	ApprovalDecision *ApprovalDecision `protobuf:"bytes,4,opt,name=approval_decision,json=approvalDecision,proto3,oneof"`
}

func (*HostMessage_Prompt) isHostMessage_Payload() {}

func (*HostMessage_ApprovalDecision) isHostMessage_Payload() {}

type UserPrompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPrompt) Reset() {
	*x = UserPrompt{}
	mi := &file_chamber_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPrompt) ProtoMessage() {}

func (x *UserPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_chamber_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPrompt.ProtoReflect.Descriptor instead.
func (*UserPrompt) Descriptor() ([]byte, []int) {
	return file_chamber_agent_proto_rawDescGZIP(), []int{2}
}

func (x *UserPrompt) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_chamber_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chamber_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_chamber_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ApprovalRequest) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ApprovalRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ApprovalRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type ApprovalDecision struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ApprovalDecision_Approved
	//	*ApprovalDecision_Denied
	Outcome       isApprovalDecision_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalDecision) Reset() {
	*x = ApprovalDecision{}
	mi := &file_chamber_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalDecision) ProtoMessage() {}

func (x *ApprovalDecision) ProtoReflect() protoreflect.Message {
	mi := &file_chamber_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalDecision.ProtoReflect.Descriptor instead.
func (*ApprovalDecision) Descriptor() ([]byte, []int) {
	return file_chamber_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ApprovalDecision) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ApprovalDecision) GetOutcome() isApprovalDecision_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ApprovalDecision) GetApproved() *Approved {
	if x != nil {
		if x, ok := x.Outcome.(*ApprovalDecision_Approved); ok {
			return x.Approved
		}
	}
	return nil
}

func (x *ApprovalDecision) GetDenied() *Denied {
	if x != nil {
		if x, ok := x.Outcome.(*ApprovalDecision_Denied); ok {
			return x.Denied
		}
	}
	return nil
}

type isApprovalDecision_Outcome interface {
	isApprovalDecision_Outcome()
}

type ApprovalDecision_Approved struct {
	Approved *Approved `protobuf:"bytes,2,opt,name=approved,proto3,oneof"`
}

type ApprovalDecision_Denied struct {
	Denied *Denied `protobuf:"bytes,3,opt,name=denied,proto3,oneof"`
}

func (*ApprovalDecision_Approved) isApprovalDecision_Outcome() {}

func (*ApprovalDecision_Denied) isApprovalDecision_Outcome() {}

type Approved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Approved) Reset() {
	*x = Approved{}
	mi := &file_chamber_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Approved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Approved) ProtoMessage() {}

func (x *Approved) ProtoReflect() protoreflect.Message {
	mi := &file_chamber_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Approved.ProtoReflect.Descriptor instead.
func (*Approved) Descriptor() ([]byte, []int) {
	return file_chamber_agent_proto_rawDescGZIP(), []int{5}
}

type Denied struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Denied) Reset() {
	*x = Denied{}
	mi := &file_chamber_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Denied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Denied) ProtoMessage() {}

func (x *Denied) ProtoReflect() protoreflect.Message {
	mi := &file_chamber_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Denied.ProtoReflect.Descriptor instead.
func (*Denied) Descriptor() ([]byte, []int) {
	return file_chamber_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Denied) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LensChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Html          string                 `protobuf:"bytes,4,opt,name=html,proto3" json:"html,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LensChanged) Reset() {
	*x = LensChanged{}
	mi := &file_chamber_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LensChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LensChanged) ProtoMessage() {}

func (x *LensChanged) ProtoReflect() protoreflect.Message {
	mi := &file_chamber_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LensChanged.ProtoReflect.Descriptor instead.
func (*LensChanged) Descriptor() ([]byte, []int) {
	return file_chamber_agent_proto_rawDescGZIP(), []int{7}
}

func (x *LensChanged) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LensChanged) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LensChanged) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *LensChanged) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

type Started struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Started) Reset() {
	*x = Started{}
	mi := &file_chamber_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Started) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Started) ProtoMessage() {}

func (x *Started) ProtoReflect() protoreflect.Message {
	mi := &file_chamber_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Started.ProtoReflect.Descriptor instead.
func (*Started) Descriptor() ([]byte, []int) {
	return file_chamber_agent_proto_rawDescGZIP(), []int{8}
}

type TextDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextDelta) Reset() {
	*x = TextDelta{}
	mi := &file_chamber_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDelta) ProtoMessage() {}

func (x *TextDelta) ProtoReflect() protoreflect.Message {
	mi := &file_chamber_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDelta.ProtoReflect.Descriptor instead.
func (*TextDelta) Descriptor() ([]byte, []int) {
	return file_chamber_agent_proto_rawDescGZIP(), []int{9}
}

func (x *TextDelta) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Completed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completed) Reset() {
	*x = Completed{}
	mi := &file_chamber_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completed) ProtoMessage() {}

func (x *Completed) ProtoReflect() protoreflect.Message {
	mi := &file_chamber_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completed.ProtoReflect.Descriptor instead.
func (*Completed) Descriptor() ([]byte, []int) {
	return file_chamber_agent_proto_rawDescGZIP(), []int{10}
}

type RuntimeError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeError) Reset() {
	*x = RuntimeError{}
	mi := &file_chamber_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeError) ProtoMessage() {}

func (x *RuntimeError) ProtoReflect() protoreflect.Message {
	mi := &file_chamber_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeError.ProtoReflect.Descriptor instead.
func (*RuntimeError) Descriptor() ([]byte, []int) {
	return file_chamber_agent_proto_rawDescGZIP(), []int{11}
}

func (x *RuntimeError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RuntimeError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RuntimeError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_chamber_agent_proto protoreflect.FileDescriptor

const file_chamber_agent_proto_rawDesc = "" +
	"\n" +
	"\x13chamber_agent.proto\x12\x10chamber.agent.v1\"\xba\x03\n" +
	"\n" +
	"AgentEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x125\n" +
	"\astarted\x18\x02 \x01(\v2\x19.chamber.agent.v1.StartedH\x00R\astarted\x12<\n" +
	"\n" +
	"text_delta\x18\x03 \x01(\v2\x1b.chamber.agent.v1.TextDeltaH\x00R\ttextDelta\x12;\n" +
	"\tcompleted\x18\x04 \x01(\v2\x1b.chamber.agent.v1.CompletedH\x00R\tcompleted\x126\n" +
	"\x05error\x18\x05 \x01(\v2\x1e.chamber.agent.v1.RuntimeErrorH\x00R\x05error\x12N\n" +
	"\x10approval_request\x18\a \x01(\v2!.chamber.agent.v1.ApprovalRequestH\x00R\x0fapprovalRequest\x12B\n" +
	"\flens_changed\x18\b \x01(\v2\x1d.chamber.agent.v1.LensChangedH\x00R\vlensChangedB\t\n" +
	"\apayloadJ\x04\b\x06\x10\a\"\xc8\x01\n" +
	"\vHostMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x126\n" +
	"\x06prompt\x18\x02 \x01(\v2\x1c.chamber.agent.v1.UserPromptH\x00R\x06prompt\x12Q\n" +
	"\x11approval_decision\x18\x04 \x01(\v2\".chamber.agent.v1.ApprovalDecisionH\x00R\x10approvalDecisionB\t\n" +
	"\apayloadJ\x04\b\x03\x10\x04\" \n" +
	"\n" +
	"UserPrompt\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"w\n" +
	"\x0fApprovalRequest\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\"\xad\x01\n" +
	"\x10ApprovalDecision\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x128\n" +
	"\bapproved\x18\x02 \x01(\v2\x1a.chamber.agent.v1.ApprovedH\x00R\bapproved\x122\n" +
	"\x06denied\x18\x03 \x01(\v2\x18.chamber.agent.v1.DeniedH\x00R\x06deniedB\t\n" +
	"\aoutcome\"\n" +
	"\n" +
	"\bApproved\" \n" +
	"\x06Denied\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"Y\n" +
	"\vLensChanged\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x12\n" +
	"\x04html\x18\x04 \x01(\tR\x04html\"\t\n" +
	"\aStarted\"\x1f\n" +
	"\tTextDelta\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\v\n" +
	"\tCompleted\"Z\n" +
	"\fRuntimeError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable2[\n" +
	"\fAgentRuntime\x12K\n" +
	"\bInteract\x12\x1d.chamber.agent.v1.HostMessage\x1a\x1c.chamber.agent.v1.AgentEvent(\x010\x01b\x06proto3"

var (
	file_chamber_agent_proto_rawDescOnce sync.Once
	file_chamber_agent_proto_rawDescData []byte
)

func file_chamber_agent_proto_rawDescGZIP() []byte {
	file_chamber_agent_proto_rawDescOnce.Do(func() {
		file_chamber_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chamber_agent_proto_rawDesc), len(file_chamber_agent_proto_rawDesc)))
	})
	return file_chamber_agent_proto_rawDescData
}

var file_chamber_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_chamber_agent_proto_goTypes = []any{
	(*AgentEvent)(nil),       // 0: chamber.agent.v1.AgentEvent
	(*HostMessage)(nil),      // 1: chamber.agent.v1.HostMessage
	(*UserPrompt)(nil),       // 2: chamber.agent.v1.UserPrompt
	(*ApprovalRequest)(nil),  // 3: chamber.agent.v1.ApprovalRequest
	(*ApprovalDecision)(nil), // 4: chamber.agent.v1.ApprovalDecision
	(*Approved)(nil),         // 5: chamber.agent.v1.Approved
	(*Denied)(nil),           // 6: chamber.agent.v1.Denied
	(*LensChanged)(nil),      // 7: chamber.agent.v1.LensChanged
	(*Started)(nil),          // 8: chamber.agent.v1.Started
	(*TextDelta)(nil),        // 9: chamber.agent.v1.TextDelta
	(*Completed)(nil),        // 10: chamber.agent.v1.Completed
	(*RuntimeError)(nil),     // 11: chamber.agent.v1.RuntimeError
}
var file_chamber_agent_proto_depIdxs = []int32{
	8,  // 0: chamber.agent.v1.AgentEvent.started:type_name -> chamber.agent.v1.Started
	9,  // 1: chamber.agent.v1.AgentEvent.text_delta:type_name -> chamber.agent.v1.TextDelta
	10, // 2: chamber.agent.v1.AgentEvent.completed:type_name -> chamber.agent.v1.Completed
	11, // 3: chamber.agent.v1.AgentEvent.error:type_name -> chamber.agent.v1.RuntimeError
	3,  // 4: chamber.agent.v1.AgentEvent.approval_request:type_name -> chamber.agent.v1.ApprovalRequest
	7,  // 5: chamber.agent.v1.AgentEvent.lens_changed:type_name -> chamber.agent.v1.LensChanged
	2,  // 6: chamber.agent.v1.HostMessage.prompt:type_name -> chamber.agent.v1.UserPrompt
	4,  // 7: chamber.agent.v1.HostMessage.approval_decision:type_name -> chamber.agent.v1.ApprovalDecision
	5,  // 8: chamber.agent.v1.ApprovalDecision.approved:type_name -> chamber.agent.v1.Approved
	6,  // 9: chamber.agent.v1.ApprovalDecision.denied:type_name -> chamber.agent.v1.Denied
	1,  // 10: chamber.agent.v1.AgentRuntime.Interact:input_type -> chamber.agent.v1.HostMessage
	0,  // 11: chamber.agent.v1.AgentRuntime.Interact:output_type -> chamber.agent.v1.AgentEvent
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_chamber_agent_proto_init() }
func file_chamber_agent_proto_init() {
	if File_chamber_agent_proto != nil {
		return
	}
	file_chamber_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentEvent_Started)(nil),
		(*AgentEvent_TextDelta)(nil),
		(*AgentEvent_Completed)(nil),
		(*AgentEvent_Error)(nil),
		(*AgentEvent_ApprovalRequest)(nil),
		(*AgentEvent_LensChanged)(nil),
	}
	file_chamber_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*HostMessage_Prompt)(nil),
		(*HostMessage_ApprovalDecision)(nil),
	}
	file_chamber_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*ApprovalDecision_Approved)(nil),
		(*ApprovalDecision_Denied)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chamber_agent_proto_rawDesc), len(file_chamber_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chamber_agent_proto_goTypes,
		DependencyIndexes: file_chamber_agent_proto_depIdxs,
		MessageInfos:      file_chamber_agent_proto_msgTypes,
	}.Build()
	File_chamber_agent_proto = out.File
	file_chamber_agent_proto_goTypes = nil
	file_chamber_agent_proto_depIdxs = nil
}
